server:
  port: 19010

apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,common

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,loggers,refresh

com:
  miotech:
    ip:
      manual-mapping:
        usCidr: 192.169.1.1/24,192.167.3.1/24